name: Build and deploy ASP.Net Core app to Azure Web App - selectu-backend

on:
  push:
    branches:
      - main
    paths:
      - 'API/**'  # Trigger only if changes occur within the 'API' folder
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.x'
          include-prerelease: true

      - name: Build and publish with dotnet
        run: |
          cd API
          dotnet build --configuration Release
          dotnet publish -c Release -o $GITHUB_WORKSPACE/SelectU.API

          # Use PowerShell to remove the test appsettings.json file
          Remove-Item -Path $GITHUB_WORKSPACE/SelectU.API/SelectU.Tests/appsettings.json -Force

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: .net-app
          path: $GITHUB_WORKSPACE/SelectU.API

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'selectu-backend'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_C271DC5D7097451D8630519549C8D933 }}
          package: .
