name: Build and deploy Angular app to Azure Web App - selectu-frontend

on:
  push:
    branches:
      - main
    paths:
      - 'Client/**'  # Trigger only if changes occur within the 'client' folder
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # Use the appropriate Node.js version

      - name: Install Angular CLI
        run: |
        cd Client
        npm install -g @angular/cli

      - name: Install dependencies and build
        run: |
          cd Client
          npm install
          ng build --configuration production

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: angular-app
          path: ./client/dist  # Adjust the path to the built frontend code

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: angular-app

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'selectu-frontend'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_2DA2AA85B04F42B9B5F8760BE95978B2 }}
          package: .
