name: Build and deploy Angular app to Azure Web App - selectu-frontend

on:
  push:
    branches:
      - main
    paths:
      - 'Client/**'  # Trigger only if changes occur within the 'client' folder
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # Use the appropriate Node.js version

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install Angular CLI using Yarn
        run: |
          cd Client
          yarn global add @angular/cli

      - name: Install dependencies using Yarn and build
        run: |
          cd Client
          yarn install
          ng build --configuration production
          
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'selectu-frontend'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_96C615F35DEC46C5882D65424EE6587C }}
          package: ./Client/dist/client
